### ISSUE TITLE
[feature request] Import local packages

### ISSUE THREAD

**Issue by clmno** [asottile/setuptools-golang#100]
In the README it is said
> An extension must be a single file in the main go package (though the entire main package will be built into the extension).

Can we do these in the current version
1. Will different files with the same package name (eg `package main`) be compiled to a extension?
2. Can we add local packages? (eg `github.com/clmno/master` and `github.com/clmno/master/child`)

If not, can we have this feature?

**Comment by asottile** [comment]
any imports will resolve, yes -- for [example](https://github.com/asottile/dockerfile/blob/4230890bcf08a0d91134898da7a671529131c6fe/pylib/main.go#L21)

the bit of docs you're reading refers to the `Extension(...)` invocation -- a limitation of `setuptools` itself

**Comment by clmno** [comment]
Oh it wan't working for me. My go version of the code works individually but when used as a py extension it doesn't. My bad, I thought it was `setuptools-golang`'s issue. Will debug further.

What I did:
I imported a local package and was printing. But this code was never called for some reason
