### ISSUE TITLE
Can this add built binaries to the PATH?

### ISSUE THREAD

**Issue by dustin-decker** [asottile/setuptools-golang#116]
I'm interested in packaging go binaries in a multi-arch pip package that should be runnable from the PATH.

Can this tool help with that?

**Comment by asottile** [comment]
not really -- that's a bit of a different problem space.  this is mostly intended to be a helper for building python-importable C extensions

for your case you'd probably need to customize the `install` setuptools command and write a script -- perhaps similar to how [dumb-init](https://github.com/yelp/dumb-init) does this

**Comment by dustin-decker** [comment]
Thanks for the pointer!
