### ISSUE TITLE
Cross-compile go library

### ISSUE THREAD

**Issue by paultop6** [asottile/setuptools-golang#118]
setuptools-golang has support for windows, mac and linux.  But this appears to only be the case for compilation on the host platform.

Is it possible to cross compile the go library for use on another system type.  E.g. compile windows compatible go library on a linux platform.

**Comment by asottile** [comment]
possible: sure anything is "possible".  easy: no, python doesn't really have facilities for cross compilation

**Comment by paultop6** [comment]
I know go has good facilities for cross compilation, just wasnt sure of the python side.
