### ISSUE TITLE
Can setuptools-golang be used to build universal2 wheels?

### ISSUE THREAD

**Issue by colindean** [asottile/setuptools-golang#155]
I'm working on getting [`starlark-go`](https://github.com/caketop/python-starlark-go) shipping a universal binary for macOS. @jordemort [speculated](https://github.com/caketop/python-starlark-go/pull/131#issuecomment-1398823588) that setuptools-golang may not have what's necessary to coax go to produce a `universal2` binary.

Is there any reason it wouldn't be working?

I'd admit I have relatively little experience using setuptools or go, so I'm reading a lot of code!

**Comment by asottile** [comment]
go itself doesn't have a mechanism for this that I know of, you can switch things together after the fact though with something like `lipo`
