### ISSUE TITLE
Build fails on Windows, maybe due to space in Python's installation path

### ISSUE THREAD

**Issue by oryarn-arpeely** [asottile/setuptools-golang#199]
Hi!

First, thank you very much for this package, it is exactly what I needed to allow compiling a small library I wrote for both MacOS and Linux.
Unfortunately, when trying to build it on Windows, the build failed with an error similar to `File Files\Python3.9\Include doesn't exist`. When inspecting the `go build` commandline - the `CGO_CFLAGS` variable add the flag `-IC:\Program Files\Python3.9\Include`, so I think that the issue is the space in the `Program Files` path.

This doesn't happen in the CI, because the python seems to be installed at `c:\hostedtoolcache\windows\python\3.8.10` which doesn't contain spaces.

I think that the issue is at https://github.com/asottile/setuptools-golang/blob/main/setuptools_golang.py#L59 which adds the include-dir flag, but doesn't try to shell-escape it.

**Comment by asottile** [comment]
feel free to send a patch if you can demonstrate it works -- though I'm pretty sure that variable doesn't support quoting anyway
