### ISSUE TITLE
macOS and Windows wheels

### ISSUE THREAD

**Issue by MaxHalford** [asottile/setuptools-golang#27]
Hey,

I've successfully managed to use `setuptools-golang` to build wheels and upload them to PyPI 🎆 

I was wondering if you've planned to also make it possible to build Windows and macOS wheels?

Regards.

**Comment by asottile** [comment]
For windows and macos nothing special is needed, just `pip wheel  . `  and upload those (manylinux is a special snowflake) 

For instance, I've uploaded wheels for [dockerfile](https://pypi.org/simple/dockerfile/)

**Comment by asottile** [comment]
@MaxHalford did this answer your question?

**Comment by MaxHalford** [comment]
Yes, sorry I forgot to close the issue.
