### ISSUE TITLE
breakages for golang 1.16

### ISSUE THREAD

**Issue by asottile** [asottile/setuptools-golang#65]
the tests are broken for golang 1.16 -- pretty sure I just need to add a `go.mod` to the tests

also setuptools-golang-examples is probably broken as well

shouldn't be too difficult to fix though

**Comment by mdillavou** [comment]
Any updates on this? Fedora 34 comes with go 1.16.x, so I am currently unable to build dockerfile (running on arm64)

**Comment by asottile** [comment]
feel free to add a `go.mod` or to use `GO111MODULE=off`

**Comment by mdillavou** [comment]
Thanks, exporting `GO111MODULE=off` worked for me.

**Comment by asottile** [comment]
probably not including your go mod if I had to guess. it's impossible to know with the information you've shown

**Comment by amoiseev** [comment]
Ok thanks, two things helped:
- Eliminating a subdirectory with CGO files (.go, .c, go.mod) and putting everything at the repo root
- Adding MANIFEST.in
