### ISSUE TITLE
Can't link on FreeBSD/macOS due to clang being used

### ISSUE THREAD

**Issue by nils-werner** [asottile/setuptools-golang#7]
Compilation fails with

    ld: unknown option: --unresolved-symbols=ignore-all
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

The temporary fix I found was to change [`CGO_LDFLAGS`](https://github.com/asottile/setuptools-golang/blob/master/setuptools_golang.py#L76) to

    'CGO_LDFLAGS': '-Wl,-undefined,dynamic_lookup',

**Comment by asottile** [comment]
Do you have a suggestion for detecting which compiler is used for the backing of `cgo`?  Currently the code assumes `gcc` which is why you get these errors under clang

**Comment by asottile** [comment]
This is now available in >=1.1.0

**Comment by asottile** [comment]
Could you try this out and see if it works?

**Comment by nils-werner** [comment]
Yup, seems to work, thanks!
