### ISSUE TITLE
Python 3.5 support? 

### ISSUE THREAD

**Issue by ColdHeat** [asottile/setuptools-golang#73]
Hi there, thanks for this library it really helps with packaging Golang based Python modules!

I'm working on supporting Python 3.5 in a project of mine so that it can be used on Raspberry Pis more easily. But it looks like the tests are failing b/c setuptools-golang doesn't support 3.5. 

https://github.com/ColdHeat/pybluemonday/pull/23
https://github.com/piwheels/packages/issues/197

I haven't dug into it yet but do you know if it's possible to support 3.5 here?  Would you accept a PR for the change?

**Comment by asottile** [comment]
[I will not be supporting end-of-lifed versions of python for free](https://github.com/asottile/scratch/wiki/python-3-statement)

setuptools-golang<2 had support for those versions -- you may be able to try that?
