### ISSUE TITLE
strip extensions for smaller modules

### ISSUE THREAD

**Issue by corka149** [asottile/setuptools-golang#90]
The modules created with Go can be big. `go build` offers the possibility to reduce size by omitting debugging information and symbols. I found out in a test that this could reduce the size of a wheel by 42 %.

My suggestion would be to add `'strip': False` to `build_golang` as a switch. This would add `'-ldflags=-s -w'` to `go build` or not.

**Comment by asottile** [comment]
is there a reason to not do this unconditionally?  I generally prefer fewer options unless someone has an explicit usecase for toggling a value

**Comment by corka149** [comment]
Sounds reasonable. I changed it so that `True` is the default value for stripping. It might become handy in case of bugs. :sweat_smile:
